### ISSUE TITLE
Qiniu\Pili\Hub中的listLiveStreams和listStreams方法一直返回bad request

### ISSUE THREAD

**Issue by keepchen** [pili-engineering/pili-sdk-php.v2#29]
# 环境
* os:ubuntu16.04 x64
* php版本:7.0
* sdk版本:pili-sdk-php.v2

# 调用:
```php
   $instance->listLiveStreams("test", 5, 0);
   //or
   $instance->listStreams("test", 5, 0);
```
# 返回值:
```json
 {"error":"bad request"}
```
@rwifeng 你好，麻烦帮忙看下是什么原因，谢谢。

**Comment by KeepChen** [comment]
# 补充：
**刚刚看了sdk源码，发现部分接口地址与官网描述存在差异**
* `Qiniu\Pili\Hub.php`第58行和60行:
```php
$url = sprintf("%s/streams?liveonly=%s&prefix=%s&limit=%d&marker=%s", $this->_baseURL, $live, $prefix, $limit, $marker);
```
```php
$ret = $this->_transport->send(HttpRequest::GET, $url);
```
**与官网文档描述的接口地址不一致，另，请求方法也不一致，官网标注POST方式，SDK中是GET方式**
[官网文档地址](https://developer.qiniu.com/pili/api/3764/batch-query-broadcast-real-time-information)
# 修改部分源码后：
>按照官网文档修改了部分源码，可以得到期望效果。
